import json
import sys
from datetime import datetime
from collections import defaultdict

def load_data(filename="sbc_trend_data.json"):
    with open(filename, 'r') as f:
        return json.load(f)

def get_trend_arrow(change):
    if change > 10:
        return "🔥🚀"
    elif change > 5:
        return "📈▲"
    elif change > 0:
        return "▲"
    elif change < -10:
        return "❄️▼"
    elif change < 0:
        return "▼"
    else:
        return "●"

def generate_report(data, weeks_to_show=1):
    """Generate a beautiful trend report"""
    
    # Sort dates
    dates = sorted(data.keys())
    latest = dates[-1]
    previous = dates[-2] if len(dates) > 1 else None
    
    # Get latest mentions
    latest_data = data[latest]
    sorted_latest = sorted(latest_data.items(), key=lambda x: x[1], reverse=True)
    
    # Build report
    report = f"""
╔══════════════════════════════════════════════════════════════════════╗
║                    ZEITVIBE SBC TREND REPORT                         ║
║                         {datetime.now().strftime('%B %d, %Y')}                         ║
╚══════════════════════════════════════════════════════════════════════╝

📊 COMMUNITY MENTIONS (Last 7 days)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

"""
    
    # Add bar chart
    for sbc, mentions in sorted_latest:
        bar_length = min(mentions // 10, 50)
        bar = "█" * bar_length
        report += f"{sbc:25} {bar} {mentions}\n"
    
    # Add weekly changes
    if previous:
        previous_data = data[previous]
        report += f"""
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📈 WEEK OVER WEEK CHANGE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

"""
        changes = []
        for sbc in latest_data:
            current = latest_data[sbc]
            prev = previous_data[sbc]
            change = ((current - prev) / prev) * 100 if prev > 0 else 0
            arrow = get_trend_arrow(change)
            changes.append((sbc, change, arrow, current, prev))
        
        # Sort by change
        changes.sort(key=lambda x: x[1], reverse=True)
        
        for sbc, change, arrow, current, prev in changes:
            report += f"{arrow} {sbc:25} {change:+.1f}%  ({prev} → {current})\n"
    
    # Add insights
    report += f"""
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🔮 ZEITVIBE INSIGHTS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

"""
    
    # Generate insights
    top_sbc = sorted_latest[0]
    report += f"🏆 MOST DISCUSSED: {top_sbc[0]} ({top_sbc[1]} mentions)\n\n"
    
    if previous:
        # Find biggest gainer
        gainers = [(sbc, ((latest_data[sbc] - previous_data[sbc]) / previous_data[sbc]) * 100) 
                   for sbc in latest_data if previous_data[sbc] > 0]
        gainers.sort(key=lambda x: x[1], reverse=True)
        if gainers:
            report += f"🔥 FASTEST GROWING: {gainers[0][0]} (+{gainers[0][1]:.0f}%)\n"
        
        # Find biggest decliner
        decliners = [(sbc, ((latest_data[sbc] - previous_data[sbc]) / previous_data[sbc]) * 100) 
                     for sbc in latest_data if previous_data[sbc] > 0]
        decliners.sort(key=lambda x: x[1])
        if decliners:
            report += f"❄️ FASTEST DECLINING: {decliners[0][0]} ({decliners[0][1]:.0f}%)\n"
    
    # NPU note
    report += f"""
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
⚡ NPU-ACCELERATED ANALYSIS | EDGE COMPUTING | REAL-TIME TRENDS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Report generated by ZeitVibe on KHADAS VIM3 (5 TOPS NPU)
Data sourced from community discussions | #SBC #Maker #EdgeAI
"""
    
    return report

def print_report():
    data = load_data()
    report = generate_report(data)
    print(report)
    
    # Save report
    with open(f"trend_report_{datetime.now().strftime('%Y%m%d')}.txt", "w") as f:
        f.write(report)
    print(f"\n📁 Report saved to trend_report_{datetime.now().strftime('%Y%m%d')}.txt")

if __name__ == "__main__":
    print_report()
